#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  emergencySwitch, sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl11, greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, redLED,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           doorMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
	Project Title: Pandamonium Door Mechanism
  Team Members: Hannan Beiken, Adrian Portillo
  Date: 01/18/2022
  Section: Pandamonium


  Task Description: Control the door to the exhibit using a motor and rotary encoder. Include a sonar, emergency switch, and red led for safety.
  									The door should stop if a panda is in the way, or the emergency switch is pressed.
 */



void LEDError() {
	//Set the LEDs in error mode (green off and red on)
	turnLEDOff(greenLED);
	turnLEDOn(redLED);
}



task flashGreenLED() {
	while (true) {
		turnLEDOn(greenLED);
		wait1Msec(250);
		turnLEDOff(greenLED);
		wait1Msec(250);
	}
}



char operateDoor(char doorState) {
	if (doorState == 'c') {
		//If the door is closed, start the motor to open it and the flash the green LED
		startMotor(doorMotor, 17);
		startTask(flashGreenLED);

		while (doorState == 'c') {
			//while the door is closing, check if emergency switch pressed and when door is closed
			if (SensorValue[emergencySwitch] == 1) {
				//if emergency pressed, stop door, set door position to open, and set LEDs to error mode
				stopMotor(doorMotor);
				LEDError();
				return 'o';
			}

			if (SensorValue[quad] >= 730)  {
				//If the door has reached the closed position, stop the motor and stop flashing the green LED.
				stopMotor(doorMotor);
				stopTask(flashGreenLED);
				return 'o';
			}
		}



	} else if (doorState == 'o') {
		//If the door is open, start the motor in the opposite way to close the door and flash the green LED.
		startMotor(doorMotor, -20);
		startTask(flashGreenLED);

		while (doorState == 'o') {
			//While door is opening, check if emergency switch pressed, door has closed, or if object in doorway
			if (SensorValue[emergencySwitch] == 1) {
				//if emergency pressed, stop door, set the door position to open, and set LEDs to error mode.
				stopMotor(doorMotor);
				LEDError();
				return 'o';
			}

			if (SensorValue[quad] <= -10) {
				//If the door has closed, stop the motor, stop flashing the green LED, and set the door position to closed.
				stopMotor(doorMotor);
				stopTask(flashGreenLED);
				return 'c';
			}

			if (SensorValue[sonar] < 10 && SensorValue[sonar] > 6) {
				//If an object is in the doorway, stop the motor, set the LEDs to error mode, and set the door position to open.
				stopMotor(doorMotor);
				LEDError();
				return 'o';
			}
		}
	} else {
		return doorState;
	}
}

task main() {
	//Make a variable showing if the door is open or closed
	char doorState = 'c';

	while (true) {
		//Set the LEDs to ready condition (green on and red off)
		turnLEDOn(greenLED);
		turnLEDOff(redLED);

		//If all conditions are clear (emergency switch not pressed, nothing in the doorway) and button is pressed, move the door
		if (SensorValue[bumpSwitch] == 1 && SensorValue[emergencySwitch] == 0 && SensorValue[sonar] > 9) {
			doorState = operateDoor(doorState);
		} else if (SensorValue[sonar] < 10 && SensorValue[sonar] > 6) {
			//If something in doorway, indicate using LEDs in error mode
			LEDError();
		}

		//If you need to reset the position of the encoder, press both the emergency switch and the button.
		if (SensorValue[bumpSwitch] == 1 && SensorValue[emergencySwitch] == 1) {
			SensorValue[quad] = 0;
		}
	}
}
