#pragma config(Sensor, dgtl1,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl2,  emergencySwitch, sensorTouch)
#pragma config(Sensor, dgtl3,  quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl11, greenLED,       sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, redLED,         sensorLEDtoVCC)
#pragma config(Motor,  port2,           doorMotor,     tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void LEDError() {
	turnLEDOff(greenLED);
	turnLEDOn(redLED);
}

void flashGreenLED() {
	turnLEDOn(greenLED);
}

char operateDoor(char doorState) {
	if (doorState == 'c') {
		startMotor(doorMotor, 15);
		turnLEDOn(greenLED);
		//while the door is closing, check if emergency switch pressed and when door is closed
		//if emergency pressed, stop door and return code open midway
		while (doorState == 'c') {

			if (SensorValue[emergencySwitch] == 1) {
				stopMotor(doorMotor);
				LEDError();
				return 'm';
			}

			if (SensorValue[quad] >= 740)  {
				stopMotor(doorMotor);
				return 'o';
			}
		}

	} else if (doorState == 'o') {
		startMotor(doorMotor, -18);
		//While door is open, check if emergency switch pressed or if object in doorway
		//if emergency pressed, stop door and return code open midway
		while (doorState == 'o') {
			if (SensorValue[emergencySwitch] == 1) {
				stopMotor(doorMotor);
				LEDError();
				return 'm';
			}

			if (SensorValue[quad] <= 0) {
				stopMotor(doorMotor);
				return 'c';
			//if object in door way or less than 10 inches from sonar, stop door and return code open midway
			}

			if (SensorValue[sonar] < 11 && SensorValue[sonar] > 5) {
				stopMotor(doorMotor);
				LEDError();
				return 'm';
			}
		}
	} else if (doorState == 'm') {
		return operateDoor('o');
	} else {
		return doorState;
	}
}

task main() {
	//replace with case switch if possible
	//quad prob doesn't keep position after reboot so door must be fully closed before shutting down
	char doorState = 'c';

	while (true) {
		turnLEDOn(greenLED);
		turnLEDOff(redLED);
		if (SensorValue[bumpSwitch] == 1 && SensorValue[emergencySwitch] == 0 && SensorValue[sonar] >= 10) {
			doorState = operateDoor(doorState);
		} else if (SensorValue[sonar] < 11 && SensorValue[sonar] > 5) {
			LEDError();
		}

		if (SensorValue[bumpSwitch] == 1 && SensorValue[emergencySwitch] == 1) {
			SensorValue[quad] = 0;
		}
	}
}
