#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLower,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Zoo Crew Inputs and Outputs Check Program 3
  Team Members: Hannan Beiken, Adrian Portillo
  Date: January 4, 2022
  Section: 3


  Task Description: Test the optical shaft encoder by controlling an output with it.


  Pseudocode: Initialize: Set the value of the encoder to 0

  						If the optical encoder is greater than 127 or less than -127 (max of servo)
  							reset the encoder value to 0
  						set the servo to the value of the encoder

*/

task main()
{

	SensorValue[encoderLower] = 0;

	while(true)
	{



		if (SensorValue[encoderLower] > 127 || SensorValue[encoderLower] < -127) {
			SensorValue[encoderLower] = 0;
		}

		setServo(servo, SensorValue[encoderLower]);



	}
}
