#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLower,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Zoo Crew Inputs and Outputs Check Program 3: Limit Switch
  Team Members: Hannan Beiken, Adrian Portillo
  Date: January 4, 2022
  Section: 3


  Task Description: Test the limit switch by controlling an output with it.


  Pseudocode: If limit switch pressed
  							start left motor
  							turn led on
  						else
  							stop left motor
  							turn led off
*/

task main()
{
	while(true)
	{



		if (SensorValue[limitSwitch] == 1)
		{
			startMotor(leftMotor, 25);
			turnLEDOn(led);
		}
		else
		{
			stopMotor(leftMotor);
			turnLEDOff(led);
		}



	}
}
