#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLower,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl12, led,            sensorLEDtoVCC)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Zoo Crew Inputs and Outputs Check Program 3
  Team Members: Hannan Beiken, Adrian Portillo
  Date: January 4, 2022
  Section: 3


  Task Description: Verify Functioning Limit Switch, Bump Switch, Optical Shaft Encoder, and LED


  Pseudocode: If limit switch pressed
  							start right motor and turn led on
  						If bump switch pressed
  							stop right motor and turn led off

  						If the optical encoder is greater than 127 or less than -127 (max of servo)
  							reset the encoder value to 0
  						set the servo to the value of the encoder

*/

task main()
{
	while(true)
	{



		if (SensorValue[limitSwitch] == 1) {
			startMotor(rightMotor, 50);
			turnLEDOn(led);
		}
		if (SensorValue[bumpSwitch] == 1) {
			stopMotor(rightMotor);
			turnLEDOff(led);
		}

		if (SensorValue[encoderLower] > 127 || SensorValue[encoderLower] < -127) {
			SensorValue[encoderLower] = 0;
		}

		setServo(servo, SensorValue[encoderLower]);



	}
}
