#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLower,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Zoo Crew Inputs and Outputs Check Program 1
  Team Members: Hannan Beiken, Adrian portillo
  Date: December 9, 2021
  Section: 1


  Task Description: Verify operation of left and right motors. Test servo with 3 movements.


  Pseudocode: When the task is set to start the motor on the right side turns at speed 50 to the right, afterwards when the command is
  over motormotor will pause for 1.5 seconds and the motor on the left will turn at speed 50 to the left, then it will stop for 1.5
  seconds and the servo will turn the gear 115 degrees to the right, next it will pause for 1 second and then turn 230 degrees to the left
  then it will pause again for 1 second and then it goes back to 0, finally it just keeps repeating the entire program until stopped.
*/

task main()
{                                     //Program begins, insert code within curly braces
	while(true)
	{
		startMotor(rightMotor, 50);
		wait1Msec(1500);
		stopMotor(rightMotor);
		startMotor(leftMotor, -50);
		wait1Msec(1500);
		stopMotor(leftMotor);
		setServo(servo, 115);
		wait1Msec(1000);
		setServo(servo, -115);
		wait1Msec(1000);
		setServo(servo, 0);
		wait1Msec(1000);
	}

}
