#pragma config(Sensor, in1,    lineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    lightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  limitSwitch,    sensorTouch)
#pragma config(Sensor, dgtl2,  bumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  encoderLower,   sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  sonar,          sensorSONAR_inch)
#pragma config(Motor,  port1,           flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servo,         tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: Zoo Crew Inputs and Outputs Check Program 1
  Team Members: Hannan Beiken, Adrian portillo
  Date: December 9, 2021
  Section: 1


  Task Description: Verify operation of left and right motors. Test servo with 3 movements.


  Pseudocode: start the right motor
  						wait a bit and stop the motor
  						start the left motor
  						wait a bit and stop the motor
  						
  						turn the servo 115 degrees
  						wait a bit
  						turn the servo 115 degrees to the other side
  						wait a bit
  						reset the servo to 0 degrees
*/

task main()
{
	while(true)
	{
		
	
	
		startMotor(rightMotor, 50);
		wait1Msec(1500);
		stopMotor(rightMotor);
		startMotor(leftMotor, -50);
		wait1Msec(1500);
		stopMotor(leftMotor);
		
		setServo(servo, 115);
		wait1Msec(1000);
		setServo(servo, -115);
		wait1Msec(1000);
		setServo(servo, 0);
		wait1Msec(1000);
		
		
		
	}
}
